### ISSUE TITLE
Compatibility with abcjs

### ISSUE THREAD

**Issue by Ksinia** [yvesgurcan/midi-instrument-patches#2]
Hello @yvesgurcan,

Aside from web-midi-player, I use abcjs to render and play music and I love this (midi-instrument-patches) piano music sound very much. I've opened an issue /paulrosen/abcjs/issues/325 about it but the author of abcjs wouldn't be able to figure out how to use this music set in the absence of readme.

Would you be so kind as to add a readme to this project and help find out how to make this amazing music set to work in abcjs in linked issue?

Thank you very much!

**Comment by yvesgurcan** [comment]
Hi, @Ksinia. I'm glad that you're enjoying the MIDI patches in this repository. I will work on adding instructions here about the files. I'm not sure, though, if it will be possible to use these patches with `abcjs`. I've started a conversation in the issue you opened on the project.

**Comment by yvesgurcan** [comment]
I've added a `README` file with more information about the instrument patches (PR #4). Unfortunately, it looks like these files are not compatible with `abcjs` since they are `.pat` files (specific to `libTimidity`) and the soundfont used by the other library (https://paulrosen.github.io/midi-js-soundfonts/) are `.js` files. Sorry about that! Let me know if you find out more.

**Comment by Ksinia** [comment]
I think having /paulrosen/abcjs/issues/325 open would be enough. Thank you a lot!

**Comment by yvesgurcan** [comment]
Thanks!
